package com.example.model

import androidx.compose.ui.graphics.Color
import com.example.ui.theme.TapoutBrightRed
import com.example.ui.theme.TapoutCrimson
import com.example.ui.theme.TapoutGold
import com.example.ui.theme.TapoutNeonBlue
import com.example.ui.theme.TapoutNeonPurple
import com.example.ui.theme.TapoutOrange

data class PersonalityTrait(
    val name: String,
    val description: String,
    val badgeColor: Color = TapoutGold,
    val ratingPct: Float = 0.85f
)

data class Fighter(
    val id: String,
    val name: String,
    val realName: String,
    val humanOrigin: String,
    val elementalState: String, // Fire, Water/Frost, Wind, Rock/Earth, Lightning, Void
    val elementSymbol: String,
    val spiritAnimal: String,
    val spiritAnimalSymbol: String,
    val elementalStrengths: String,
    val elementalWeaknesses: String,
    val title: String,
    val style: String,
    val era: String,
    val personality: String,
    val traits: List<PersonalityTrait>,
    val combatPhilosophy: String,
    val timelineOrigin: String,
    val homeStageId: String,
    val maxHp: Int,
    val speed: Float,
    val jumpPower: Float,
    val punchDamage: Int,
    val kickDamage: Int,
    val specialDamage: Int,
    val specialName: String,
    val signatureMoveDescription: String,
    val finalBlowMeleeSmashName: String,
    val finalBlowSmashDescription: String,
    val finalBlowSmashQuote: String,
    val weaponEquipment: String,
    val themeColor: Color,
    val accentColor: Color,
    val avatarCode: String,
    val statPower: Float,     // 0.0 to 1.0
    val statSpeed: Float,     // 0.0 to 1.0
    val statDefense: Float,   // 0.0 to 1.0
    val statSpecial: Float,   // 0.0 to 1.0
    val introQuote: String,
    val tauntQuote: String,
    val specialQuote: String,
    val victoryQuote: String,
    val bio: String,
    val storyArc: String,
    val rivalFighterName: String,
    val dialoguePrologue: String,
    val dialogueVsRival: String,
    val dialogueRivalResponse: String
)

object Roster {
    val fighters: List<Fighter> = listOf(
        Fighter(
            id = "ninja",
            name = "SHADOW NINJA",
            realName = "Renzo Takahashi",
            humanOrigin = "Human Shinobi Grandmaster",
            elementalState = "VOID & SHADOW",
            elementSymbol = "🌌",
            spiritAnimal = "PHANTOM PANTHER",
            spiritAnimalSymbol = "🐆",
            elementalStrengths = "WIND (+25%) & ROCK (+20%)",
            elementalWeaknesses = "LIGHTNING (-25%) & WATER (-20%)",
            title = "THE PHANTOM BLADE",
            style = "NINJUTSU & VOID SHADOWSTEP",
            era = "1580 FEUDAL KYOTO",
            personality = "Calm, lethal, disciplined, and mysterious.",
            traits = listOf(
                PersonalityTrait("Silent Focus", "Maintains absolute stillness until the lethal strike window opens.", TapoutNeonPurple, 0.95f),
                PersonalityTrait("Shadow Discipline", "Adheres to the ancient Shinobi oath of stealth, evasion, and concealment.", TapoutNeonBlue, 0.90f),
                PersonalityTrait("Phantom Panther Instinct", "Spirit animal grants 360-degree spatial awareness in pitch darkness.", TapoutGold, 0.92f),
                PersonalityTrait("Spacetime Weaver", "Manipulates void rips in space to evade kinetic counter-attacks effortlessly.", Color(0xFFE080FF), 0.88f)
            ),
            combatPhilosophy = "The blade you do not see is the one that decides your fate. True power lies in flow, deception, and precise lethal execution.",
            timelineOrigin = "Feudal Kyoto Mountain Hermitage • Sengoku Jidai Era (1580)",
            homeStageId = "stage1",
            maxHp = 100,
            speed = 3.3f,
            jumpPower = 11.5f,
            punchDamage = 13,
            kickDamage = 20,
            specialDamage = 38,
            specialName = "VOID BLADE DASH",
            signatureMoveDescription = "Dashes instantaneously through quantum rift dimensions, slashing through opponent guard with twin void kunai blades.",
            finalBlowMeleeSmashName = "VOID PANTHER ECLIPSE SMASH",
            finalBlowSmashDescription = "Awakens the spectral Void Panther spirit, vanishing into dark matter before delivering a 7-hit aerial dimensional cross-slash.",
            finalBlowSmashQuote = "BEHOLD THE FANGS OF THE VOID PANTHER!",
            weaponEquipment = "Twin Spacetime Kunai, Smoke Bombs & Shadow Silk Cowl",
            themeColor = TapoutNeonPurple,
            accentColor = Color(0xFFE080FF),
            avatarCode = "01",
            statPower = 0.70f,
            statSpeed = 0.95f,
            statDefense = 0.65f,
            statSpecial = 0.90f,
            introQuote = "Step into darkness... your blade cannot cut what it cannot see.",
            tauntQuote = "You swing at ghosts. Is this your best?",
            specialQuote = "VOID RIFT SHADOW CRUSH!",
            victoryQuote = "A true shadow leaves no trace upon the battlefield.",
            bio = "Renzo was once an ordinary human monk in Kyoto until discovering the celestial rift scrolls. Awakening the Void Panther spirit within, his human speed transcends the laws of physics.",
            storyArc = "Seeking to restore his destroyed ninja clan by claiming the Chrono Core at the tournament pinnacle.",
            rivalFighterName = "TITAN MMA",
            dialoguePrologue = "The Kyoto temple bells echo across the temporal void. My Panther spirit stirs...",
            dialogueVsRival = "Vance... your synthetic wires and steel cannot cage the ancient Void Panther!",
            dialogueRivalResponse = "Data analysis shows your spirit magic is nothing more than unharnessed electromagnetic anomalies, Renzo!"
        ),
        Fighter(
            id = "mma",
            name = "TITAN MMA",
            realName = "Marcus Vance",
            humanOrigin = "Human Cyber-Enhanced Athlete",
            elementalState = "LIGHTNING & PLASMA",
            elementSymbol = "⚡",
            spiritAnimal = "THUNDER CYBER-TIGER",
            spiritAnimalSymbol = "🐅",
            elementalStrengths = "WATER (+30%) & VOID (+25%)",
            elementalWeaknesses = "ROCK (-25%) & FIRE (-20%)",
            title = "CYBERNETIC OCTAGON KING",
            style = "CYBER FREESTYLE COMBAT",
            era = "2099 NEO TOKYO",
            personality = "Aggressive, confident, calculated, and high-tech.",
            traits = listOf(
                PersonalityTrait("Overclocked Drive", "Pushes neural implants past safety thresholds for blinding reaction times.", TapoutBrightRed, 0.96f),
                PersonalityTrait("Thunder Tiger Stalk", "Generates static plasma charges with every step to amplify strike power.", TapoutOrange, 0.92f),
                PersonalityTrait("Data-Driven Striking", "Simulates 10,000 punch vectors per second using tactical AI telemetry.", TapoutGold, 0.88f),
                PersonalityTrait("Titan Armor", "Synthetic carbon skeleton absorbs blunt impact and redistributes force.", Color(0xFFFF9966), 0.85f)
            ),
            combatPhilosophy = "Victory is a mathematical certainty when power, hydraulic velocity, and cybernetic precision converge.",
            timelineOrigin = "Neo Tokyo Underground Octagon Dome • Cyber Epoch (2099)",
            homeStageId = "stage2",
            maxHp = 120,
            speed = 2.6f,
            jumpPower = 10.0f,
            punchDamage = 16,
            kickDamage = 24,
            specialDamage = 42,
            specialName = "TITAN IMPACT KNEE",
            signatureMoveDescription = "Fires hydraulic micro-thrusters in his cybernetic knee joints, delivering a hyper-velocity flying knee strike.",
            finalBlowMeleeSmashName = "HYPER-VOLT TIGER MELEE SMASH",
            finalBlowSmashDescription = "Overclocks neural plasma capacitors, summoning a roaring 10,000-volt Cyber-Tiger aura that detonates an explosive ground-pound.",
            finalBlowSmashQuote = "SYSTEM OVERDRIVE: TIGER FANG CATACLYSM!",
            weaponEquipment = "Titanium-Tungsten Fist Plating & Kinetic Overdrive Kneepads",
            themeColor = TapoutBrightRed,
            accentColor = Color(0xFFFF9966),
            avatarCode = "02",
            statPower = 0.85f,
            statSpeed = 0.75f,
            statDefense = 0.80f,
            statSpecial = 0.85f,
            introQuote = "My cyber-servos are overclocked. You're going to sleep in round 1.",
            tauntQuote = "Calculating victory probability: 99.8%. Give up.",
            specialQuote = "MAXIMUM THRUST TITAN OVERDRIVE!",
            victoryQuote = "Calculated knockout. Just as my neural engine simulated.",
            bio = "Born in the slums of Neo Tokyo, Marcus Vance modified his biological body with hydraulic cybernetics, fusing his fierce human fighting spirit with the Thunder Tiger neural matrix.",
            storyArc = "Fighting to prove human-synthetic hybrid supremacy across all mortal history.",
            rivalFighterName = "IRON BOXER",
            dialoguePrologue = "Neural link online. Octagon telemetry calibrated. Time to show these relics true future power.",
            dialogueVsRival = "Sullivan! Your 1970s leather gloves are antique toys against 2099 plasma hydraulics!",
            dialogueRivalResponse = "Toys? Boy, my left hook will knock those shiny computer chips right out of your skull!"
        ),
        Fighter(
            id = "boxer",
            name = "IRON BOXER",
            realName = "Jack 'Thunder' Sullivan",
            humanOrigin = "Human Heavyweight Champion",
            elementalState = "WIND & CYCLONE",
            elementSymbol = "🌪️",
            spiritAnimal = "STORM FALCON",
            spiritAnimalSymbol = "🦅",
            elementalStrengths = "ROCK (+25%) & WATER (+20%)",
            elementalWeaknesses = "FIRE (-25%) & VOID (-20%)",
            title = "THE BRONX THUNDERBOLT",
            style = "CLASSIC HEAVYWEIGHT BOXING",
            era = "1974 BROOKLYN BRONX",
            personality = "Gritty, charismatic, resilient, and fearless.",
            traits = listOf(
                PersonalityTrait("Indestructible Grit", "Never backs down, drawing greater punching power when pinned against the ropes.", TapoutNeonBlue, 0.94f),
                PersonalityTrait("Falcon Reflexes", "Reads opponent shoulder twitches to bob and weave under heavy hooks.", TapoutGold, 0.90f),
                PersonalityTrait("Iron Chin", "Shrugs off heavy concussive blows that would knock ordinary combatants cold.", TapoutCrimson, 0.92f),
                PersonalityTrait("Old-School Heart", "Values pure sweat, raw heart, and honest fist-to-fist fighting spirit.", Color(0xFF80EEFF), 0.88f)
            ),
            combatPhilosophy = "Float like thunder, strike like an earthquake. A real champion gets knocked down six times and stands back up seven.",
            timelineOrigin = "74th Precinct Boxing Club, Brooklyn NYC • Golden Age (1974)",
            homeStageId = "stage3",
            maxHp = 110,
            speed = 2.8f,
            jumpPower = 9.5f,
            punchDamage = 18,
            kickDamage = 16,
            specialDamage = 40,
            specialName = "DRAGON UPPERCUT",
            signatureMoveDescription = "Dips low in bob-and-weave stance, gathering explosive ground torque into a thunderous upward hook launching rivals airborne.",
            finalBlowMeleeSmashName = "CYCLONE FALCON DECIMATION HOOK",
            finalBlowSmashDescription = "Channels willpower into the soaring Storm Falcon, creating a roaring hurricane vortex around fists before detonating a knockout blow.",
            finalBlowSmashQuote = "EAT A BROOKLYN HURRICANE! KNOCKOUT!",
            weaponEquipment = "Vintage Hand-Wrapped Leather Boxing Gloves & Brass Belt Buckle",
            themeColor = TapoutNeonBlue,
            accentColor = Color(0xFF80EEFF),
            avatarCode = "03",
            statPower = 0.90f,
            statSpeed = 0.85f,
            statDefense = 0.70f,
            statSpecial = 0.80f,
            introQuote = "Hands up, chin down. Let's see if you can take a Brooklyn hook!",
            tauntQuote = "Come on! My grandma hits harder than that!",
            specialQuote = "TAKE A FLIGHT WITH THE DRAGON UPPERCUT!",
            victoryQuote = "Down goes another contender! Ring the bell, ref!",
            bio = "A working-class human fighter from the hard streets of Brooklyn. When pushed to the brink, Jack awakens the Storm Falcon—turning his fists into gale-force hammers.",
            storyArc = "Transported mid-championship bout into the time arena, Jack fights to bring the belt back to 1974.",
            rivalFighterName = "COLOSSEUM GRAPPLER",
            dialoguePrologue = "Smell that? Sweat, leather, and glory. No bell rings until only one man is standing.",
            dialogueVsRival = "Maximus! Keep those giant gladiator paws off me or I'll slip inside and crack your ribs!",
            dialogueRivalResponse = "Hah! A man with padded mittens challenges the Roman Colosseum? I shall throw you to Jupiter!"
        ),
        Fighter(
            id = "wrestler",
            name = "COLOSSEUM GRAPPLER",
            realName = "Maximus of Thrace",
            humanOrigin = "Human Roman Champion Gladiator",
            elementalState = "EARTH & ROCK",
            elementSymbol = "🪨",
            spiritAnimal = "COLOSSAL GOLDEN BULL",
            spiritAnimalSymbol = "🐂",
            elementalStrengths = "LIGHTNING (+30%) & FIRE (+20%)",
            elementalWeaknesses = "WIND (-20%) & VOID (-25%)",
            title = "THE IMPERIAL LION",
            style = "GRECO-ROMAN OLYMPIAN",
            era = "79 AD ANCIENT ROME",
            personality = "Honorable, roaring, proud, and mighty.",
            traits = listOf(
                PersonalityTrait("Gladiator Pride", "Commands the arena crowd with roaring charisma and Roman glory.", TapoutGold, 0.96f),
                PersonalityTrait("Golden Bull Charge", "Channels unstoppable momentum that ignores enemy light attacks.", TapoutCrimson, 0.98f),
                PersonalityTrait("Martial Honor", "Refuses cowardly strikes, demanding face-to-face heavy grappling duels.", Color(0xFFFFF080), 0.89f),
                PersonalityTrait("Indomitable Mass", "Anchors himself to the arena sand like a fortress tower against knockbacks.", TapoutOrange, 0.94f)
            ),
            combatPhilosophy = "The earth will yield before a true gladiator does. Throw your foe with the weight of the heavens and let the crowd roar.",
            timelineOrigin = "Flavian Amphitheatre (Colosseum), Imperial Rome • Classical Antiquity (79 AD)",
            homeStageId = "stage4",
            maxHp = 135,
            speed = 2.2f,
            jumpPower = 9.0f,
            punchDamage = 14,
            kickDamage = 22,
            specialDamage = 48,
            specialName = "SEISMIC OLYMPIA SUPLEX",
            signatureMoveDescription = "Grips the opponent in a vice bearhug, vaults backwards with Herculean power, and crashes them headfirst into bedrock.",
            finalBlowMeleeSmashName = "TITAN BULL SEISMIC MELEE CRUSH",
            finalBlowSmashDescription = "Summons the roaring Golden Bull of Olympus, stomping tectonic shockwaves before crushing the target in an unstoppable suplex smash.",
            finalBlowSmashQuote = "BY HERCULES AND MARS: TASTE IMPERIAL GRANITE!",
            weaponEquipment = "Gilded Gladiator Cestus, Golden Laurel Crown & Imperial Shoulder Plate",
            themeColor = TapoutGold,
            accentColor = Color(0xFFFFF080),
            avatarCode = "04",
            statPower = 0.98f,
            statSpeed = 0.60f,
            statDefense = 0.95f,
            statSpecial = 0.92f,
            introQuote = "By Mars and Jupiter, I shall break your resolve against the sand!",
            tauntQuote = "Is that the blow of a warrior or a frightened child?",
            specialQuote = "FEEL THE WRATH OF OLYMPUS!",
            victoryQuote = "Glory to Rome! The arena belongs to the undefeated lion!",
            bio = "A human warrior born to the arena sand. Through relentless gladiatorial combat, Maximus bonded with the ancient Golden Bull spirit, hardening his human flesh into living granite.",
            storyArc = "Summoned to the time nexus to claim divine immortality from the tournament creators.",
            rivalFighterName = "VOLCANIC WARLORD",
            dialoguePrologue = "The sands of the amphitheater call to me. Glory shall be mine!",
            dialogueVsRival = "Ignis! Your wild fire may melt lesser men, but Roman rock stands immortal!",
            dialogueRivalResponse = "Rock turns into liquid magma when my flame burns at full heat, Roman fool!"
        ),
        Fighter(
            id = "valkyrie",
            name = "CYBER VALKYRIE",
            realName = "Astrid Lindholm",
            humanOrigin = "Human Astral Fighter Ace",
            elementalState = "WATER & FROST ICE",
            elementSymbol = "❄️",
            spiritAnimal = "AURORA FROST DRAGON",
            spiritAnimalSymbol = "🐉",
            elementalStrengths = "FIRE (+30%) & VOID (+25%)",
            elementalWeaknesses = "LIGHTNING (-25%) & WIND (-20%)",
            title = "ASTRAL SHIELD MAIDEN",
            style = "SYNTHETIC VALHALLA COMBAT",
            era = "2140 VALKYRIE CORPS",
            personality = "Noble, swift, futuristic, and laser-focused.",
            traits = listOf(
                PersonalityTrait("Astral Precision", "Channels plasma particles along magnetic rail conduits for instantaneous thrust.", Color(0xFF00E5FF), 0.93f),
                PersonalityTrait("Frost Dragon Roar", "Chills atmospheric temperature to slow enemy strike velocity.", TapoutNeonPurple, 0.89f),
                PersonalityTrait("Valkyrie Oath", "Sworn to safeguard the space-time continuum from temporal chaos rifts.", TapoutGold, 0.92f),
                PersonalityTrait("Photon Aegis", "Projects electromagnetic force barriers that deflect energy projectiles.", Color(0xFFB3FFFF), 0.91f)
            ),
            combatPhilosophy = "Precision conquers brute savagery. We strike with the speed of northern lights and defend with the fortress of the cosmos.",
            timelineOrigin = "Orbital Station Asgard-9 • Valkyrie Fleet Frontier (2140)",
            homeStageId = "stage7",
            maxHp = 105,
            speed = 3.1f,
            jumpPower = 11.0f,
            punchDamage = 15,
            kickDamage = 21,
            specialDamage = 44,
            specialName = "AURORA PLASMA SPEAR",
            signatureMoveDescription = "Summons an ionized aurora plasma lance, projecting a concentrated beam of solar energy across the arena.",
            finalBlowMeleeSmashName = "GLACIAL DRAGON ASTRAL MELEE DIVE",
            finalBlowSmashDescription = "Unleashes the cryo-astral Frost Dragon, freezing the arena floor before executing a supersonic aerial lance strike shattering target defenses.",
            finalBlowSmashQuote = "FROST DRAGON ASCENSION: FREEZE THE TIMELINE!",
            weaponEquipment = "Photon Valkyrie Wings, Plasma Rail Lance & Asgardian Force Shield",
            themeColor = Color(0xFF00E5FF),
            accentColor = Color(0xFFB3FFFF),
            avatarCode = "05",
            statPower = 0.82f,
            statSpeed = 0.90f,
            statDefense = 0.75f,
            statSpecial = 0.88f,
            introQuote = "Scanning combat parameters... Target acquisition locked. Engage!",
            tauntQuote = "Telemetry confirms: your fighting pattern is obsolete.",
            specialQuote = "AURORA PLASMA DISCHARGE!",
            victoryQuote = "Target neutralized. Recording telemetry to the Valkyrie mainframe.",
            bio = "A human elite test pilot from the Valkyrie Corps who bonded with the Frost Dragon. Astrid combines human tactical military training with glacial elemental mastery.",
            storyArc = "Tasked with containing temporal anomalies threatening the stability of the 22nd century.",
            rivalFighterName = "SHADOW NINJA",
            dialoguePrologue = "Asgard-9 telemetry locked. Spatial rupture detected. Engaging tournament perimeter.",
            dialogueVsRival = "Renzo! Thermal and cryo scanners have locked onto your void frequency. You cannot hide!",
            dialogueRivalResponse = "Scanners only see what light touches, Valkyrie. The void has no heat to read."
        ),
        Fighter(
            id = "warlord",
            name = "VOLCANIC WARLORD",
            realName = "Ignis Kahn",
            humanOrigin = "Human Magma Clan Chieftain",
            elementalState = "FIRE & MAGMA",
            elementSymbol = "🔥",
            spiritAnimal = "MOLTEN LAVA PHOENIX",
            spiritAnimalSymbol = "🦚",
            elementalStrengths = "WIND (+25%) & LIGHTNING (+25%)",
            elementalWeaknesses = "WATER (-30%) & ROCK (-20%)",
            title = "SCORCHED EARTH BERSERKER",
            style = "LAVA CRUSHING BRAWLER",
            era = "ERA OF FLAME",
            personality = "Furious, explosive, commanding, and relentless.",
            traits = listOf(
                PersonalityTrait("Molten Berserk", "Ignites superheated magma veins in his fists when taking battle damage.", TapoutOrange, 0.98f),
                PersonalityTrait("Phoenix Rebirth Aura", "Unleashes blazing heat waves when HP drops below 30%.", TapoutBrightRed, 0.95f),
                PersonalityTrait("Seismic Dominance", "Stomps shatter the ground, creating eruptive fissures under enemy footing.", TapoutGold, 0.94f),
                PersonalityTrait("Cataclysmic Will", "Believes peace is weakness and only eternal conflict tempers true warriors.", Color(0xFFFF5500), 0.95f)
            ),
            combatPhilosophy = "All things return to ash and magma. Those who hesitate are consumed by the furnace of war.",
            timelineOrigin = "Subterranean Magma Caldera Chambers • Primeval Flame Epoch",
            homeStageId = "stage8",
            maxHp = 130,
            speed = 2.4f,
            jumpPower = 9.2f,
            punchDamage = 17,
            kickDamage = 23,
            specialDamage = 46,
            specialName = "MAGMA ERUPTION SLAM",
            signatureMoveDescription = "Punches deep into the ground, detonating a concentrated volcanic pillar beneath the opponent.",
            finalBlowMeleeSmashName = "MOLTEN PHOENIX INFERNO MELEE SMASH",
            finalBlowSmashDescription = "Manifests the wings of the Primeval Lava Phoenix, rocketing into the sky before crashing into the opponent with a colossal pyroclastic explosion.",
            finalBlowSmashQuote = "BURN IN THE PHOENIX INFERNO! ASH TO ASH!",
            weaponEquipment = "Obsidian-Lava Gauntlets, Molten Spiked Pauldrons & Flame Core",
            themeColor = TapoutOrange,
            accentColor = Color(0xFFFF5500),
            avatarCode = "06",
            statPower = 0.94f,
            statSpeed = 0.68f,
            statDefense = 0.88f,
            statSpecial = 0.94f,
            introQuote = "Burn in the crucible of battle! Nothing survives the eruption!",
            tauntQuote = "You are kindling waiting for my flame!",
            specialQuote = "HELLFIRE VOLCANIC CATACLYSM!",
            victoryQuote = "Ash to ash! The fire consumes all weakness!",
            bio = "A human warlord who survived the volcanic cataclysms of the primal age. Drinking from the molten caldera springs, he awakened the Lava Phoenix spirit to turn his human fists into erupting magma.",
            storyArc = "Seeking to engulf the multiverse in an eternal cleansing flame.",
            rivalFighterName = "COLOSSEUM GRAPPLER",
            dialoguePrologue = "The magma in my veins boils. These warriors are brittle twigs before my furnace!",
            dialogueVsRival = "Maximus! Your gladiator stone will melt into glowing lava before my fists!",
            dialogueRivalResponse = "Rome was built on stone that outlasts all fires, Ignis! Feel the weight of the Colosseum!"
        )
    )

    fun getFighterById(id: String): Fighter =
        fighters.find { it.id == id } ?: fighters.first()
}
