package com.example.model

import androidx.compose.ui.graphics.Color
import com.example.ui.theme.TapoutBrightRed
import com.example.ui.theme.TapoutCrimson
import com.example.ui.theme.TapoutGold
import com.example.ui.theme.TapoutNeonBlue
import com.example.ui.theme.TapoutNeonPurple
import com.example.ui.theme.TapoutOrange

data class Fighter(
    val id: String,
    val name: String,
    val title: String,
    val style: String,
    val era: String,
    val personality: String,
    val homeStageId: String,
    val maxHp: Int,
    val speed: Float,
    val jumpPower: Float,
    val punchDamage: Int,
    val kickDamage: Int,
    val specialDamage: Int,
    val specialName: String,
    val themeColor: Color,
    val accentColor: Color,
    val avatarCode: String,
    val statPower: Float,     // 0.0 to 1.0
    val statSpeed: Float,     // 0.0 to 1.0
    val statDefense: Float,   // 0.0 to 1.0
    val statSpecial: Float,   // 0.0 to 1.0
    val introQuote: String,
    val specialQuote: String,
    val victoryQuote: String,
    val bio: String,
    val storyArc: String
)

object Roster {
    val fighters: List<Fighter> = listOf(
        Fighter(
            id = "ninja",
            name = "SHADOW NINJA",
            title = "THE PHANTOM BLADE",
            style = "NINJUTSU & SHADOWSTEP",
            era = "1580 FEUDAL KYOTO",
            personality = "Calm, lethal, disciplined, and mysterious.",
            homeStageId = "stage1",
            maxHp = 100,
            speed = 3.3f,
            jumpPower = 11.5f,
            punchDamage = 13,
            kickDamage = 20,
            specialDamage = 38,
            specialName = "VOID BLADE DASH",
            themeColor = TapoutNeonPurple,
            accentColor = Color(0xFFE080FF),
            avatarCode = "01",
            statPower = 0.70f,
            statSpeed = 0.95f,
            statDefense = 0.65f,
            statSpecial = 0.90f,
            introQuote = "Step into darkness... your blade cannot cut what it cannot see.",
            specialQuote = "VOID RIFT SHADOW CRUSH!",
            victoryQuote = "A true shadow leaves no trace upon the battlefield.",
            bio = "Trained in the mountain cloisters of Kyoto, Renzo was chosen by the sacred clan elders to investigate spacetime tears that were abducting warriors. Moving silently between dimensions, he wields twin chakra kunai that cut through kinetic barriers.",
            storyArc = "Seeking to restore his destroyed ninja village by claiming the Chrono Core at the top of the Celestial Pantheon tournament."
        ),
        Fighter(
            id = "mma",
            name = "TITAN MMA",
            title = "CYBERNETIC OCTAGON KING",
            style = "CYBER FREESTYLE COMBAT",
            era = "2099 NEO TOKYO",
            personality = "Aggressive, confident, calculated, and high-tech.",
            homeStageId = "stage2",
            maxHp = 120,
            speed = 2.6f,
            jumpPower = 10.0f,
            punchDamage = 16,
            kickDamage = 24,
            specialDamage = 42,
            specialName = "TITAN IMPACT KNEE",
            themeColor = TapoutBrightRed,
            accentColor = Color(0xFFFF9966),
            avatarCode = "02",
            statPower = 0.85f,
            statSpeed = 0.75f,
            statDefense = 0.80f,
            statSpecial = 0.85f,
            introQuote = "My cyber-servos are overclocked. You're going to sleep in round 1.",
            specialQuote = "MAXIMUM THRUST TITAN OVERDRIVE!",
            victoryQuote = "Calculated knockout. Just as my neural engine simulated.",
            bio = "Marcus Vance dominated the zero-gravity underground cage leagues of 2099. Upgraded with carbon-fiber reinforced bones and hydraulic knee actuators, his striking power rivals industrial demolition machinery.",
            storyArc = "Fighting to prove human-synthetic hybrid supremacy across all mortal history."
        ),
        Fighter(
            id = "boxer",
            name = "IRON BOXER",
            title = "THE BRONX THUNDERBOLT",
            style = "CLASSIC HEAVYWEIGHT BOXING",
            era = "1974 BROOKLYN BRONX",
            personality = "Gritty, charismatic, resilient, and fearless.",
            homeStageId = "stage3",
            maxHp = 110,
            speed = 2.8f,
            jumpPower = 9.5f,
            punchDamage = 18,
            kickDamage = 16,
            specialDamage = 40,
            specialName = "DRAGON UPPERCUT",
            themeColor = TapoutNeonBlue,
            accentColor = Color(0xFF80EEFF),
            avatarCode = "03",
            statPower = 0.90f,
            statSpeed = 0.85f,
            statDefense = 0.70f,
            statSpecial = 0.80f,
            introQuote = "Hands up, chin down. Let's see if you can take a Brooklyn hook!",
            specialQuote = "TAKE A FLIGHT WITH THE DRAGON UPPERCUT!",
            victoryQuote = "Down goes another contender! Ring the bell, ref!",
            bio = "Jack 'Thunder' Sullivan rose from cold Brooklyn basements to the world heavyweight championship. Known for his devastating slip-and-counter punches and indestructible chin, he never backs down from any clash.",
            storyArc = "Transported mid-championship bout into the time arena, Jack fights to bring the ultimate belt back to 1974."
        ),
        Fighter(
            id = "wrestler",
            name = "COLOSSEUM GRAPPLER",
            title = "THE IMPERIAL LION",
            style = "GRECO-ROMAN OLYMPIAN",
            era = "79 AD ANCIENT ROME",
            personality = "Honorable, roaring, proud, and mighty.",
            homeStageId = "stage4",
            maxHp = 135,
            speed = 2.2f,
            jumpPower = 9.0f,
            punchDamage = 14,
            kickDamage = 22,
            specialDamage = 48,
            specialName = "SEISMIC OLYMPIA SUPLEX",
            themeColor = TapoutGold,
            accentColor = Color(0xFFFFF080),
            avatarCode = "04",
            statPower = 0.98f,
            statSpeed = 0.60f,
            statDefense = 0.95f,
            statSpecial = 0.92f,
            introQuote = "By Mars and Jupiter, I shall break your resolve against the sand!",
            specialQuote = "FEEL THE WRATH OF OLYMPUS!",
            victoryQuote = "Glory to Rome! The arena belongs to the undefeated lion!",
            bio = "Maximus of Thrace conquered every coliseum from Alexandria to Rome. Crowned with laurel wreaths by emperors, his superhuman grip and seismic slams shake the earth beneath his opponents.",
            storyArc = "Summoned to the time nexus to claim divine immortality from the tournament creators."
        ),
        Fighter(
            id = "valkyrie",
            name = "CYBER VALKYRIE",
            title = "ASTRAL SHIELD MAIDEN",
            style = "SYNTHETIC VALHALLA COMBAT",
            era = "2140 VALKYRIE CORPS",
            personality = "Noble, swift, futuristic, and laser-focused.",
            homeStageId = "stage7",
            maxHp = 105,
            speed = 3.1f,
            jumpPower = 11.0f,
            punchDamage = 15,
            kickDamage = 21,
            specialDamage = 44,
            specialName = "AURORA PLASMA SPEAR",
            themeColor = Color(0xFF00E5FF),
            accentColor = Color(0xFFB3FFFF),
            avatarCode = "05",
            statPower = 0.82f,
            statSpeed = 0.90f,
            statDefense = 0.75f,
            statSpecial = 0.88f,
            introQuote = "Scanning combat parameters... Target acquisition locked. Engage!",
            specialQuote = "AURORA PLASMA DISCHARGE!",
            victoryQuote = "Target neutralized. Recording telemetry to the Valkyrie mainframe.",
            bio = "Engineered as the apex guardian unit of the orbital station Asgard-9, Astrid channels high-energy plasma arcs into supersonic aerial strikes and kinetic force shields.",
            storyArc = "Tasked with containing temporal anomalies threatening the stability of the 22nd century."
        ),
        Fighter(
            id = "warlord",
            name = "VOLCANIC WARLORD",
            title = "SCORCHED EARTH BERSERKER",
            style = "LAVA CRUSHING BRAWLER",
            era = "ERA OF FLAME",
            personality = "Furious, explosive, commanding, and relentless.",
            homeStageId = "stage8",
            maxHp = 130,
            speed = 2.4f,
            jumpPower = 9.2f,
            punchDamage = 17,
            kickDamage = 23,
            specialDamage = 46,
            specialName = "MAGMA ERUPTION SLAM",
            themeColor = TapoutOrange,
            accentColor = Color(0xFFFF5500),
            avatarCode = "06",
            statPower = 0.94f,
            statSpeed = 0.68f,
            statDefense = 0.88f,
            statSpecial = 0.94f,
            introQuote = "Burn in the crucible of battle! Nothing survives the eruption!",
            specialQuote = "HELLFIRE VOLCANIC CATACLYSM!",
            victoryQuote = "Ash to ash! The fire consumes all weakness!",
            bio = "Born in the subterranean caldera chambers beneath burning rift faults, Ignis commands molten kinetic fury that superheats his fists to blast through solid iron.",
            storyArc = "Seeking to engulf the multiverse in an eternal cleansing flame."
        )
    )

    fun getFighterById(id: String): Fighter =
        fighters.find { it.id == id } ?: fighters.first()
}
