/**
 * Time Tournament - Fighters Roster & Personality Trait Database
 */
export const FIGHTERS = [
  {
    id: "ninja",
    name: "SHADOW NINJA",
    title: "THE PHANTOM BLADE",
    style: "NINJUTSU & SHADOWSTEP",
    era: "1580 FEUDAL KYOTO",
    personality: "Calm, lethal, disciplined, and mysterious.",
    timelineOrigin: "Feudal Kyoto Mountain Hermitage • Sengoku Jidai Era (1580)",
    homeStageId: "stage1",
    maxHp: 100,
    speed: 3.3,
    jumpPower: 11.5,
    punchDamage: 13,
    kickDamage: 20,
    specialDamage: 38,
    specialName: "VOID BLADE DASH",
    signatureMove: "Dashes through quantum rift dimensions, slicing enemy guard with twin void kunai blades.",
    weapons: "Twin Spacetime Kunai, Smoke Bombs & Shadow Silk Cowl",
    color: "#C026D3",
    accent: "#E080FF",
    code: "01",
    statPower: 0.70,
    statSpeed: 0.95,
    statDefense: 0.65,
    statSpecial: 0.90,
    introQuote: "Step into darkness... your blade cannot cut what it cannot see.",
    tauntQuote: "You swing at ghosts. Is this your best?",
    specialQuote: "VOID RIFT SHADOW CRUSH!",
    victoryQuote: "A true shadow leaves no trace upon the battlefield.",
    combatPhilosophy: "The blade you do not see is the one that decides your fate. True power lies in flow, deception, and precise lethal execution without wasted motion.",
    bio: "Trained in the mountain cloisters of Kyoto, Renzo was chosen by sacred clan elders to investigate spacetime tears abducting warriors. Moving silently between dimensions, he wields twin chakra kunai that cut through kinetic barriers.",
    storyArc: "Seeking to restore his destroyed ninja village by claiming the Chrono Core at the top of the Celestial Pantheon tournament.",
    rival: "TITAN MMA",
    traits: [
      { name: "Silent Focus", desc: "Maintains absolute stillness in heart and breath until the lethal strike window opens.", color: "#C026D3", pct: 0.95 },
      { name: "Shadow Discipline", desc: "Adheres to the ancient Shinobi oath of stealth, evasion, and temporal concealment.", color: "#00E5FF", pct: 0.90 },
      { name: "Ancestral Honor", desc: "Fights exclusively to restore his fallen clan and avenge the Kyoto monastery breach.", color: "#FFC837", pct: 0.85 },
      { name: "Spacetime Weaver", desc: "Manipulates void rips in space to evade kinetic counter-attacks effortlessly.", color: "#E080FF", pct: 0.88 }
    ]
  },
  {
    id: "mma",
    name: "TITAN MMA",
    title: "CYBERNETIC OCTAGON KING",
    style: "CYBER FREESTYLE COMBAT",
    era: "2099 NEO TOKYO",
    personality: "Aggressive, confident, calculated, and high-tech.",
    timelineOrigin: "Neo Tokyo Underground Octagon Dome • Cyber Epoch (2099)",
    homeStageId: "stage2",
    maxHp: 120,
    speed: 2.6,
    jumpPower: 10.0,
    punchDamage: 16,
    kickDamage: 24,
    specialDamage: 42,
    specialName: "TITAN IMPACT KNEE",
    signatureMove: "Fires hydraulic micro-thrusters in cybernetic knees delivering hyper-velocity strikes.",
    weapons: "Titanium-Tungsten Fist Plating & Kinetic Overdrive Kneepads",
    color: "#FF1A5E",
    accent: "#FF9966",
    code: "02",
    statPower: 0.85,
    statSpeed: 0.75,
    statDefense: 0.80,
    statSpecial: 0.85,
    introQuote: "My cyber-servos are overclocked. You're going to sleep in round 1.",
    tauntQuote: "Calculating victory probability: 99.8%. Give up.",
    specialQuote: "MAXIMUM THRUST TITAN OVERDRIVE!",
    victoryQuote: "Calculated knockout. Just as my neural engine simulated.",
    combatPhilosophy: "Victory is a mathematical certainty when power, hydraulic velocity, and cybernetic precision converge. Brute force meets synthetic evolution.",
    bio: "Marcus Vance dominated zero-gravity underground cage leagues. Upgraded with carbon-fiber reinforced bones and hydraulic knee actuators, his striking power rivals industrial demolition machinery.",
    storyArc: "Fighting to prove human-synthetic hybrid supremacy across all mortal history.",
    rival: "IRON BOXER",
    traits: [
      { name: "Overclocked Drive", desc: "Pushes neural implants past safety thresholds for blinding reaction times.", color: "#FF1A5E", pct: 0.96 },
      { name: "Data-Driven Striking", desc: "Simulates 10,000 punch vectors per second using tactical AI telemetry.", color: "#FF7020", pct: 0.92 },
      { name: "Unshakable Ego", desc: "Believes biological warriors from the past are obsolete relics.", color: "#FFC837", pct: 0.88 },
      { name: "Titan Armor", desc: "Synthetic carbon skeleton absorbs blunt impact and redistributes force as bursts.", color: "#FF9966", pct: 0.85 }
    ]
  },
  {
    id: "boxer",
    name: "IRON BOXER",
    title: "THE BRONX THUNDERBOLT",
    style: "CLASSIC HEAVYWEIGHT BOXING",
    era: "1974 BROOKLYN BRONX",
    personality: "Gritty, charismatic, resilient, and fearless.",
    timelineOrigin: "74th Precinct Boxing Club, Brooklyn NYC • Golden Age (1974)",
    homeStageId: "stage3",
    maxHp: 110,
    speed: 2.8,
    jumpPower: 9.5,
    punchDamage: 18,
    kickDamage: 16,
    specialDamage: 40,
    specialName: "DRAGON UPPERCUT",
    signatureMove: "Dips low in bob-and-weave stance, detonating explosive upward hook launching rivals airborne.",
    weapons: "Vintage Hand-Wrapped Leather Boxing Gloves & Brass Belt Buckle",
    color: "#00E5FF",
    accent: "#80EEFF",
    code: "03",
    statPower: 0.90,
    statSpeed: 0.85,
    statDefense: 0.70,
    statSpecial: 0.80,
    introQuote: "Hands up, chin down. Let's see if you can take a Brooklyn hook!",
    tauntQuote: "Come on! My grandma hits harder than that!",
    specialQuote: "TAKE A FLIGHT WITH THE DRAGON UPPERCUT!",
    victoryQuote: "Down goes another contender! Ring the bell, ref!",
    combatPhilosophy: "Float like thunder, strike like an earthquake. A real champion gets knocked down six times and stands back up seven. No fancy gadgets—just raw hooks.",
    bio: "Jack 'Thunder' Sullivan rose from cold Brooklyn basements to the world heavyweight championship. Known for devastating slip-and-counter punches and an indestructible chin.",
    storyArc: "Transported mid-championship bout into the time arena, Jack fights to bring the belt back to 1974.",
    rival: "COLOSSEUM GRAPPLER",
    traits: [
      { name: "Indestructible Grit", desc: "Draws greater punching power when pinned against the ropes.", color: "#00E5FF", pct: 0.94 },
      { name: "Street Smart Instincts", desc: "Reads body weight shifts with boxing reflexes honed in 500 street bouts.", color: "#FFC837", pct: 0.90 },
      { name: "Iron Chin", desc: "Shrugs off concussive blows that would knock ordinary combatants cold.", color: "#E60045", pct: 0.92 },
      { name: "Old-School Heart", desc: "Values pure sweat, raw heart, and honest fist-to-fist fighting spirit.", color: "#80EEFF", pct: 0.88 }
    ]
  },
  {
    id: "wrestler",
    name: "COLOSSEUM GRAPPLER",
    title: "THE IMPERIAL LION",
    style: "GRECO-ROMAN OLYMPIAN",
    era: "79 AD ANCIENT ROME",
    personality: "Honorable, roaring, proud, and mighty.",
    timelineOrigin: "Flavian Amphitheatre, Imperial Rome • Classical Antiquity (79 AD)",
    homeStageId: "stage4",
    maxHp: 135,
    speed: 2.2,
    jumpPower: 9.0,
    punchDamage: 14,
    kickDamage: 22,
    specialDamage: 48,
    specialName: "SEISMIC OLYMPIA SUPLEX",
    signatureMove: "Grips opponent in bearhug, vaults backwards with Herculean power crashing them headfirst.",
    weapons: "Gilded Gladiator Cestus, Golden Laurel Crown & Imperial Plate",
    color: "#FFC837",
    accent: "#FFF080",
    code: "04",
    statPower: 0.98,
    statSpeed: 0.60,
    statDefense: 0.95,
    statSpecial: 0.92,
    introQuote: "By Mars and Jupiter, I shall break your resolve against the sand!",
    tauntQuote: "Is that the blow of a warrior or a frightened child?",
    specialQuote: "FEEL THE WRATH OF OLYMPUS!",
    victoryQuote: "Glory to Rome! The arena belongs to the undefeated lion!",
    combatPhilosophy: "The earth will yield before a true gladiator does. Throw your foe with the weight of the heavens and let the crowd roar their tribute.",
    bio: "Maximus of Thrace conquered every coliseum from Alexandria to Rome. Crowned with laurel wreaths by emperors, his superhuman grip and seismic slams shake the earth.",
    storyArc: "Summoned to the time nexus to claim divine immortality from the tournament creators.",
    rival: "VOLCANIC WARLORD",
    traits: [
      { name: "Gladiator Pride", desc: "Commands the arena crowd with roaring charisma and Roman glory.", color: "#FFC837", pct: 0.96 },
      { name: "Titan Grip", desc: "Once locked in a hold, escape is impossible without divine intervention.", color: "#E60045", pct: 0.98 },
      { name: "Martial Honor", desc: "Refuses cowardly strikes, demanding face-to-face heavy grappling duels.", color: "#FFF080", pct: 0.89 },
      { name: "Indomitable Mass", desc: "Anchors to arena sand like a fortress tower against knockbacks.", color: "#FF7020", pct: 0.94 }
    ]
  },
  {
    id: "valkyrie",
    name: "CYBER VALKYRIE",
    title: "ASTRAL SHIELD MAIDEN",
    style: "SYNTHETIC VALHALLA COMBAT",
    era: "2140 VALKYRIE CORPS",
    personality: "Noble, swift, futuristic, and laser-focused.",
    timelineOrigin: "Orbital Station Asgard-9 • Valkyrie Fleet Frontier (2140)",
    homeStageId: "stage7",
    maxHp: 105,
    speed: 3.1,
    jumpPower: 11.0,
    punchDamage: 15,
    kickDamage: 21,
    specialDamage: 44,
    specialName: "AURORA PLASMA SPEAR",
    signatureMove: "Summons ionized aurora plasma lance projecting concentrated solar energy beams.",
    weapons: "Photon Valkyrie Wings, Plasma Rail Lance & Asgardian Force Shield",
    color: "#00E5FF",
    accent: "#B3FFFF",
    code: "05",
    statPower: 0.82,
    statSpeed: 0.90,
    statDefense: 0.75,
    statSpecial: 0.88,
    introQuote: "Scanning combat parameters... Target acquisition locked. Engage!",
    tauntQuote: "Telemetry confirms: your fighting pattern is obsolete.",
    specialQuote: "AURORA PLASMA DISCHARGE!",
    victoryQuote: "Target neutralized. Recording telemetry to the Valkyrie mainframe.",
    combatPhilosophy: "Precision conquers brute savagery. We strike with the speed of northern lights and defend with the fortress of the cosmos.",
    bio: "Engineered as apex guardian unit of orbital station Asgard-9, Astrid channels high-energy plasma arcs into supersonic aerial strikes and kinetic force shields.",
    storyArc: "Tasked with containing temporal anomalies threatening stability of the 22nd century.",
    rival: "SHADOW NINJA",
    traits: [
      { name: "Astral Precision", desc: "Channels plasma particles along magnetic rail conduits for instantaneous thrust.", color: "#00E5FF", pct: 0.93 },
      { name: "Strategic Sovereignty", desc: "Calculates battlefield vectors from high-altitude tactical scans.", color: "#C026D3", pct: 0.89 },
      { name: "Valkyrie Oath", desc: "Sworn to safeguard space-time continuum from temporal warlords and chaos rifts.", color: "#FFC837", pct: 0.92 },
      { name: "Photon Aegis", desc: "Projects electromagnetic force barriers that deflect energy projectiles.", color: "#B3FFFF", pct: 0.91 }
    ]
  },
  {
    id: "warlord",
    name: "VOLCANIC WARLORD",
    title: "SCORCHED EARTH BERSERKER",
    style: "LAVA CRUSHING BRAWLER",
    era: "ERA OF FLAME",
    personality: "Furious, explosive, commanding, and relentless.",
    timelineOrigin: "Subterranean Magma Caldera Chambers • Primeval Flame Epoch",
    homeStageId: "stage8",
    maxHp: 130,
    speed: 2.4,
    jumpPower: 9.2,
    punchDamage: 17,
    kickDamage: 23,
    specialDamage: 46,
    specialName: "MAGMA ERUPTION SLAM",
    signatureMove: "Punches into the ground detonating a volcanic pillar blasting enemies skyward.",
    weapons: "Obsidian-Lava Gauntlets, Molten Spiked Pauldrons & Flame Core",
    color: "#FF7020",
    accent: "#FF5500",
    code: "06",
    statPower: 0.94,
    statSpeed: 0.68,
    statDefense: 0.88,
    statSpecial: 0.94,
    introQuote: "Burn in the crucible of battle! Nothing survives the eruption!",
    tauntQuote: "You are kindling waiting for my flame!",
    specialQuote: "HELLFIRE VOLCANIC CATACLYSM!",
    victoryQuote: "Ash to ash! The fire consumes all weakness!",
    combatPhilosophy: "All things return to ash and magma. Those who hesitate are consumed by the furnace of war. Strike until only molten rock remains.",
    bio: "Born in subterranean caldera chambers beneath burning rift faults, Ignis commands molten kinetic fury that superheats his fists to blast through solid iron.",
    storyArc: "Seeking to engulf the multiverse in an eternal cleansing flame.",
    rival: "COLOSSEUM GRAPPLER",
    traits: [
      { name: "Molten Berserk", desc: "Ignites superheated magma veins in fists when taking battle damage.", color: "#FF7020", pct: 0.98 },
      { name: "Seismic Dominance", desc: "Stomps shatter the ground, creating eruptive fissures under enemy footing.", color: "#FF1A5E", pct: 0.94 },
      { name: "Unstoppable Onslaught", desc: "Marches through defenses with the weight of an active pyroclastic surge.", color: "#FFC837", pct: 0.91 },
      { name: "Cataclysmic Will", desc: "Believes peace is weakness and only eternal conflict tempers true warriors.", color: "#FF5500", pct: 0.95 }
    ]
  }
];
